<?php

function login_register_menu() {
    $items['user_login'] = array(
      'page callback' => 'login_register_info',
      'access callback' => TRUE,
      );
    return $items;
}

function login_register_info() {

  global $user;
  $login = drupal_get_form('user_login');
  $register = drupal_get_form('user_register_form');
  $dog = drupal_get_form('user_pass');

  $output = '<div class="col-md-6">';
  $output .= drupal_render($login);
  $output .= '<div class="wechat">wechat</div>';
  $output .= '<div class="facebook">facebook</div>';
  $output .= '</div>';
  $output .= '<div class="col-md-6">';
  $output .= drupal_render($register);
  $output .= '</div>';
  
  return $output;

  //return "login register page information";
}

